name = "Nomad Tech"
license = "MIT"
licenselink = "https://github.com/m03315/nomad-tech/blob/main/LICENSE"
description = "A modern Hugo theme designed for digital nomads and tech professionals"
homepage = "https://github.com/m03315/nomad-tech"
demosite = "https://m03315.github.io/nomad-tech"
tags = ["blog", "portfolio", "multilingual", "responsive", "dark", "nomad", "tech"]
features = ["blog", "portfolio", "multilingual", "responsive", "seo", "analytics"]
min_version = "0.120.0"

[author]
  name = "m03315"
  homepage = "https://github.com/m03315"

[original]
  name = "m03315"
  homepage = "https://github.com/m03315"
  repo = "https://github.com/m03315/nomad-tech"