name: Hugo CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build and Test
        run: |
          mkdir -p exampleSite/themes/nomad-tech
          rsync -av --exclude='exampleSite' . exampleSite/themes/nomad-tech/
          cd exampleSite
          hugo --minify --buildDrafts --baseURL "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hugo-site
          path: exampleSite/public/
          retention-days: 1

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: hugo-site
          path: ./public
          
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4